#!/bin/bash

SRC='src/'
MAIN='minecraft_linux.c'
TEST='tester.c'
CFLAGS='-Wall -Wextra'
LIBS='-lraylib -lm'
PLATFORM=''

set -xe
if [ "$1" == "win" ]; then
	MAIN='minecraft_win.c'
	PLATFORM='_win.exe';
fi
time gcc $SRC$MAIN $CFLAGS $LIBS -o minecraft$PLATFORM
time gcc $SRC$TEST $CFLAGS $LIBS -o test$PLATFORM
