#ifndef ENGINE_DIAGNOSTICS_H
#define ENGINE_DIAGNOSTICS_H

#include "defines.h"
#include "limits.h"

#define DIAGNOSTIC_COLOR_DEFAULT    0xecececff
#define DIAGNOSTIC_COLOR_FATAL      0xa33021ff
#define DIAGNOSTIC_COLOR_ERROR      0xcc5829ff
#define DIAGNOSTIC_COLOR_WARNING    0xa3729eff
#define DIAGNOSTIC_COLOR_INFO       0x8fccccff
#define DIAGNOSTIC_COLOR_DEBUG      0xccccccff
#define DIAGNOSTIC_COLOR_TRACE      0xc4ae29ff
#define DIAGNOSTIC_COLOR_SUCCESS    0x6ccc49ff

#define ENGINE_ERR_OFFSET 4096

enum EngineErrorCodes
{
    ERR_SUCCESS = 0,
    ERR_POINTER_NULL = ENGINE_ERR_OFFSET,
    ERR_POINTER_NOT_NULL,
    ERR_BUFFER_EMPTY,
    ERR_BUFFER_FULL,
    ERR_BUFFER_OVERFLOW,
    ERR_FILE_NOT_FOUND,
    ERR_DIR_NOT_FOUND,
    ERR_IS_NOT_FILE,
    ERR_IS_NOT_DIR,
    ERR_FILE_OPEN_FAIL,
    ERR_DIR_OPEN_FAIL,
    ERR_FILE_EXISTS,
    ERR_DIR_EXISTS,
    ERR_SOURCE_NOT_CHANGE,
    ERR_PATH_TOO_LONG,
    ERR_STRING_TOO_LONG,
    ERR_PROCESS_FORK_FAIL,
    ERR_EXEC_FAIL,
    ERR_EXEC_PROCESS_NON_ZERO,
    ERR_EXEC_TERMINATE_BY_SIGNAL,
    ERR_EXEC_ABNORMAL_EXIT,
    ERR_WAITPID_FAIL,
    ERR_MEM_ALLOC_FAIL,
    ERR_MEM_REALLOC_FAIL,
    ERR_MEM_MAP_FAIL,
    ERR_GET_PATH_ABSOLUTE_FAIL,
    ERR_GET_PATH_BIN_ROOT_FAIL,
    ERR_MEM_COMMIT_FAIL,
    ERR_LOGGER_INIT_FAIL,
    ERR_GLFW,
    ERR_GLFW_INIT_FAIL,
    ERR_GLFW_RAW_MOUSE_MOTION_NOT_SUPPORT,
    ERR_WINDOW_INIT_FAIL,
    ERR_GLAD_INIT_FAIL,
    ERR_GL_VERSION_NOT_SUPPORT,
    ERR_SHADER_COMPILE_FAIL,
    ERR_SHADER_PROGRAM_LINK_FAIL,
    ERR_FBO_INIT_FAIL,
    ERR_FBO_REALLOC_FAIL,
    ERR_IMAGE_LOAD_FAIL,
    ERR_IMAGE_SIZE_TOO_SMALL,
    ERR_FONT_INIT_FAIL,
    ERR_TEXT_INIT_FAIL,
    ERR_MESH_GENERATION_FAIL,
    ERR_COUNT,
}; /* EngineErrorCodes */

/* declared by the user */
extern u32 engine_err;

extern str *logger_buf;

#endif /* ENGING_DIAGNOSTICS_H */
