#include "deps/fossil/common/types.h"

#include "h/common.h"

u32 DEATH_STRINGS_MAX[PLAYER_DEATH_REASON_COUNT] =
{
    DEATH_STRING_COLLISION_WALL_COUNT,
    DEATH_STRING_COLLISION_FLOOR_COUNT,
    DEATH_STRING_COLLISION_CEILING_COUNT,
};

str str_death_collision_wall[DEATH_STRING_COLLISION_WALL_COUNT][DEATH_STRING_MAX] =
{
    DEATH_STRING_COLLISION_WALL_0,
    DEATH_STRING_COLLISION_WALL_1,
    DEATH_STRING_COLLISION_WALL_2,
};

str str_death_collision_floor[DEATH_STRING_COLLISION_FLOOR_COUNT][DEATH_STRING_MAX] =
{
    DEATH_STRING_COLLISION_FLOOR_0,
    DEATH_STRING_COLLISION_FLOOR_1,
    DEATH_STRING_COLLISION_FLOOR_2,
};

str str_death_collision_ceiling[DEATH_STRING_COLLISION_CEILING_COUNT][DEATH_STRING_MAX] =
{
    DEATH_STRING_COLLISION_CEILING_0,
    DEATH_STRING_COLLISION_CEILING_1,
    DEATH_STRING_COLLISION_CEILING_2,
};
